<?php
declare( strict_types = 1 );

namespace App\Presenters;

use App\Model\Orm;
use Nette;

/**
 * Base presenter for all application presenters.
 */
abstract class BasePresenter extends Nette\Application\UI\Presenter {
    
    /** @var Orm\Orm @inject */
    public $orm;
    
    protected function startup() {
        if(!$this->user->isLoggedIn() && $this->presenter->getName() !== 'Sign'){
            $this->flashMessage('Debes iniciar sesión primero');
            $this->redirect('Sign:in');
        }
        parent::startup(); // TODO: Change the autogenerated stub
        $this->template->usuario = $this->getDbUser();
    }
    
    /**
     * Usuario de la base de datos una vez conectado
     *
     * @return Orm\Usuario|NULL
     */
    protected function getDbUser() {
        return $this->orm->usuarios->getById($this->user->getId());
    }

//    protected $database;
//    public function __construct(Nette\Database\Context $database){
//        $this->database = $database;
//    }
}
